version: "3.8"

services:
  chief-db:
    container_name: mychiefcook-db
    image: postgres:15.0-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/home
      - chief-db-vol:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  chief-db-vol:
